### ISSUE TITLE
Broken single quote symbol

### ISSUE THREAD

**Issue by yangzai** [scala/vscode-scala-syntax#10]
If a single quote symbol begins with a non alphanumeric character it would turn the highlighting red until the next single quote is encountered.

![screenshot 2018-12-18 at 9 37 22 pm](https://user-images.githubusercontent.com/2064190/50158042-f7e5c700-030d-11e9-946d-06a70db932cb.png)

Also, perhaps auto closing quote should be disabled for single quotes since they are mostly used for symbols.

**Comment by olafurpg** [comment]
This fix has now been released as part of 0.3.2, thank you for reporting!
