### ISSUE TITLE
Highlight `as` in givens

### ISSUE THREAD

**Issue by nicolasstucki** [scala/vscode-scala-syntax#103]
```scala
  given foo as Foo = ...
  given as Foo = ...
  given (x: X) as Foo = ...
  given [X](x: X) as Foo = ...
  given foo(x: X) as Foo = ...
  given foo[X](x: X) as Foo = ...
```

**Comment by nicolasstucki** [comment]
Syntax highlighting for this is particularly complex as the rule needs to identify both the `given` and the `as`. This implies that the  rule would also be in charge of highlighting everything in between. Unfortunately we can have arbitrarily complex code within the parameters.

**Comment by nicolasstucki** [comment]
@odersky, when discussing all the different syntaxes of the `given` feature we missed this small but critical aspect of the syntax.

**Comment by MaximeKjaer** [comment]
My (WIP) implementation for this feature in Pygments is able to correctly highlight this as of [this commit](https://github.com/MaximeKjaer/pygments/commit/0312dad1d31870ba76f2c3aeb5e91a595d92ef77). The idea is to rely more on state transition than regexes. We go to a `given` state on `(given)(\s+)`, and pop that state on `(as)(\s+)` or `\{`. While in that state, we highlight `\(`, `\[` and identifiers as for a `def`.

![image](https://user-images.githubusercontent.com/990794/86541874-dc063e00-bf10-11ea-85b0-aa21104363b8.png)

**Comment by nicolasstucki** [comment]
@MaximeKjaer here are some trickier ones that you might want to check in `pygments`
```scala
    given foo[X <: Y { type A = 1; def f(using a: Int): 2 }](x: X = 2) as Foo = ...
    given (using x: X = "abs")(using y: Y = s"y: $x", y: Char = if true then 'a' else 2) as Foo = ...
```

**Comment by MaximeKjaer** [comment]
Thank you! It currently fails miserably in my implementation for Pygments, but I've added them as test cases for now!

![image](https://user-images.githubusercontent.com/990794/86625725-d61e6480-bfc5-11ea-85de-cdff9a57d290.png)

(the pink for strings is correct, just a weird color choice of the Pygments theme; the red is error tokens)
