### ISSUE TITLE
String interpolation highlighting

### ISSUE THREAD

**Issue by hugo-vrijswijk** [scala/vscode-scala-syntax#11]
Interpolated string are not highlighted at the moment, the whole string is shown as a single colour. It'd be great to have interpolated variables highlighted.

![example](https://user-images.githubusercontent.com/10114577/51826794-2d57da00-22e8-11e9-8935-5d502f0e633d.png)

**Comment by olafurpg** [comment]
Fixed in #24 by @PanAeon 🎉
