### ISSUE TITLE
Import Highlighting

### ISSUE THREAD

**Issue by nickhudkins** [scala/vscode-scala-syntax#110]
I am slowly trying to move to VS Code for my Scala development, but one thing that still stands out to me is the lack of highlighting within `imports`. This is only relevant because I am coming from Intelli-J where the highlighting of `imports` is far more verbose.
<img width="2147" alt="Screen Shot 2020-06-30 at 10 15 29 PM" src="https://user-images.githubusercontent.com/299126/86195927-ff4f7880-bb1f-11ea-8541-93a608075d64.png">

I have never worked on a syntax highlighting project, but am happy to dig in if this is a desired change!

Thanks for all of the work, this is an incredible improvement to my computer's battery life and fan noise 🤣

**Comment by PanAeon** [comment]
Hi @nickhudkins, 

The class highlighting could be easily done by matching first uppercase character. But for others stuff I think Intellij uses semantic highlighting. I.e. it runs the code against actual scala parser and its own version of presentation compiler to get methods, objects and interfaces.

This project uses regex rules to get token information so atm it's impossible to distinguish for example between class `Foo` and interface `Bar` if there's no additional context, that is keyword `trait` before the interface name.
 
If you need that kind of highlighting you can check [vscode tree sitter plugin](https://marketplace.visualstudio.com/items?itemName=georgewfraser.vscode-tree-sitter). But it's in the preview stage and might not work as expected. 

Also there's a semantic highlighting for vscode spec, which might be implemented by metals for example, but it is not finalized if I'm not mistaken.

**Comment by nicolasstucki** [comment]
This is the best we can do with syntactic highlighting

<img width="226" alt="Screenshot 2020-07-01 at 15 01 58" src="https://user-images.githubusercontent.com/3648029/86246782-d674c500-bbab-11ea-9489-0fb04b6f731b.png">

**Comment by nickhudkins** [comment]
@PanAeon and @nicolasstucki, thanks so much for the explanation :) You've resolved my concerns, and it looks like @nicolasstucki already has a PR open to make an improvement here!

**Comment by nicolasstucki** [comment]
Yes, I just edited that pattern a couple of days ago an knew exactly what to do.
