### ISSUE TITLE
Extension token is incorrectly highlighted as keyword instead of identifier

### ISSUE THREAD

**Issue by olafurpg** [scala/vscode-scala-syntax#141]
The `extension` token is incorrectly highlighted as a keyword in the screenshot below

![Screenshot 2020-09-04 at 10 14 05](https://user-images.githubusercontent.com/1408093/92217049-71816800-ee97-11ea-8e3d-ec8984ed23e1.png)

I expected `extension` to be highlighted as an identifier. cc/ @nicolasstucki

**Comment by nicolasstucki** [comment]
This comes from the old rule to highlight the `extension on` syntax that has been removed a couple of releases ago. We can just drop the old syntax highlighting.
