### ISSUE TITLE
Use another format for tmLanguage

### ISSUE THREAD

**Issue by PanAeon** [scala/vscode-scala-syntax#15]
Can we use something different then `tmLangage` ?

The xml syntax makes it super hard to read, and prevents me personally to make any contributions. 

The file format is very simple, so we can use `CSON`, `YAML`, `typescript`, `scala` ... as a source language, that would be compiled by some very simple pipeline to the `tmLanguage` file, or event better to the `tmLanguage.json` file (which can be validated against json schema).

I think the chosen format should support at least comments and string interpolation, without string interpolation complex regexes become super tangled. Also we can use plain yaml as template and interpolate variables with a preprocessor (but native support is better).

See [dhall-tmlanguage.ts](https://github.com/PanAeon/vscode-language-dhall/blob/master/src/typescript/dhall-tmlanguage.ts) for imperfect example of what I mean.

Of course I can do it locally and contribute the resulting `tmLanguage` file, but then I risk getting superficial changes because I can't guarantee the exact order of fields in the file.

**Comment by torkelrogstad** [comment]
Seconded that this is a good idea. I've spent a couple of hours today struggling with the XML file, and it's one of the most frustrating experiences I've had in a while.

**Comment by olafurpg** [comment]
Thank you for reporting! I'm open for this idea, I agree the dhall-tmlanguage.ts example looks more maintainable. @PanAeon would you be interested in contributing the translation?

**Comment by PanAeon** [comment]
@olafurpg sure! I think I'm going to use a typescript DSL which would output a transient tmLanguage.json file, similar to the example above. Good thing about typescript is that people don't have to install any extra tools.

**Comment by olafurpg** [comment]
Sounds good to me, we're using TypeScript in the Metals extension and it works great. wdyt @nicolasstucki?

BTW, I apologize the slow responses and releases in this repo. It hasn't been exactly clear who's responsible for maintaining this repo so far but I hope we can improve on that in the coming weeks and months.
