### ISSUE TITLE
Inconsistent coloring for variable names in a multiple variable `val` statement

### ISSUE THREAD

**Issue by soronpo** [scala/vscode-scala-syntax#153]
Notice in the following example `x1` is colored differently than `x2` and `x3`
```scala
class Foo {
  val x1, x2, x3 = 0
}
```
![image](https://user-images.githubusercontent.com/8167952/99400105-3ff13800-28ef-11eb-9777-b77db83e46d0.png)

**Comment by nicolasstucki** [comment]
We might need to handle these ones in the same way (i.e. without) coloring.
```scala
val x1, x2, x3 = ...
val (x1, x2, x3) = ...
val (None, Some(x2), x3) = ...
```

The only way to make this one work with colors is using look behind for the 2nd, 3rd, ... variables. But this feature is still missing in JS.
