### ISSUE TITLE
Highlight all soft modifiers

### ISSUE THREAD

**Issue by odersky** [scala/vscode-scala-syntax#155]
Not highlighted currently:

    transparent   infix  open

**Comment by odersky** [comment]
Also, with at the end.

**Comment by nicolasstucki** [comment]
These are soft modifiers http://dotty.epfl.ch/docs/reference/soft-modifier.html

**Comment by nicolasstucki** [comment]
The current soft modifiers are: `inline`, `opaque`, `open`, `transparent` and `infix`

They should all be handled in a similar way.
