### ISSUE TITLE
Move PR tests to GitHub actions

### ISSUE THREAD

**Issue by nicolasstucki** [scala/vscode-scala-syntax#160]
Lately, Travis has been slow/stuck while testing PRs. 

I propose to we start testing in each PR on GitHub and Travis and later decide what to do.

**Comment by MaximeKjaer** [comment]
I think we should decide to move completely to GitHub Actions, and abandon Travis. 

It seems that after recent [announcements](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing) that Travis would be cutting back on OSS builds, they have been [running only 400 builds at a time](https://www.traviscistatus.com/#month). This is down from 500 on November 19th, and it used to be a lot higher before November. This results in backlogs of 3-10K jobs on weekdays. I think the Travis slowness is unfortunately here to stay.

**Comment by MaximeKjaer** [comment]
I've started working on this: https://github.com/MaximeKjaer/vscode-scala-syntax/blob/gh-actions/.github/workflows/build.yml
