### ISSUE TITLE
Remove code snippets

### ISSUE THREAD

**Issue by nicolasstucki** [scala/vscode-scala-syntax#18]
After discussions at a Scala Center meeting, the following conclusion was reached the conclusion
- snippets extension should be removed, leave it to community to maintain. It's OK to install multiple snippet extensions so it's fine to have multiple competing community extensions.
- syntax rules stays in the repo because it's not possible to have a multiple Scala syntax extensions.

_Originally posted by @nicolasstucki in https://github.com/scala/vscode-scala-syntax/pull/17#issuecomment-487127970_

**Comment by olafurpg** [comment]
I haven't unpublished the snippet extension yet. I consulted with @gabro how to best handle this situation and he recommended to publish a new update

- changing the name to mention the package is deprecated
- updating the readme explaining that this package is no longer maintained and users are encouraged to publish their own snippet extension.

wdyt @nicolasstucki ?
