### ISSUE TITLE
Failed to publish 0.5.1

### ISSUE THREAD

**Issue by nicolasstucki** [scala/vscode-scala-syntax#187]
See https://github.com/scala/vscode-scala-syntax/runs/1733572597?check_suite_focus=true

**Comment by nicolasstucki** [comment]
@MaximeKjaer did you see a similar error before?

**Comment by nicolasstucki** [comment]
I received an email from GitHub after this saying 
> Basic authentication using a password to Git is deprecated and will soon no longer work. Visit https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information around suggested workarounds and removal dates.

**Comment by MaximeKjaer** [comment]
No, haven't seen this before. I am able to replicate locally.

It seems that `github-changes` has [released a major version recently](https://github.com/lalitkapoor/github-changes/releases), which included a refactor that probably introduced a bug. The lesson here is that we shouldn't use `npx` in CI scripts, as major releases risk breaking our CI. I'll submit a PR that pins the version of the dependency; this seems to fix the problem locally.
