### ISSUE TITLE
Publish new version

### ISSUE THREAD

**Issue by torkelrogstad** [scala/vscode-scala-syntax#19]
Is it possible to publish a new version of this plugin? The fixes in #16 are a nice convenience I'd appreciate a lot.

**Comment by olafurpg** [comment]
Thanks for reporting! I agree it's way overdue to release a new version of this extension @nicolasstucki do you have publish rights for the scala-lang organization on the VS Code Marketplace?

**Comment by nicolasstucki** [comment]
Yes, I will publish a new version

**Comment by olafurpg** [comment]
There's a new v0.3.0 release out now :tada: https://marketplace.visualstudio.com/items?itemName=scala-lang.scala

We have configured the CI release on tag push so that future changes will not have to wait as long for another release.

**Comment by torkelrogstad** [comment]
Awesome, thanks for being so responsive guys. Appreciate it!
