### ISSUE TITLE
"val" in "end val" is highlighted as an identifier, not a keyword

### ISSUE THREAD

**Issue by MaximeKjaer** [scala/vscode-scala-syntax#192]
![image](https://user-images.githubusercontent.com/990794/105504344-ef6bd180-5cc7-11eb-9eb4-bd38304a9474.png)

See: https://dotty.epfl.ch/docs/reference/other-new-features/indentation.html

**Comment by nicolasstucki** [comment]
Probably just need to add `val` here https://github.com/scala/vscode-scala-syntax/blob/c63623da07bc1f91645651be97fa127e1e863745/src/typescript/Scala.tmLanguage.ts#L587
