### ISSUE TITLE
Q: Possible to derive from this a Scala based lexer?

### ISSUE THREAD

**Issue by Sciss** [scala/vscode-scala-syntax#204]
Hi there. Since I'm not very familiar with VS Code, or the regex mechanisms of JS / TS, I wanted to query your opinion if the definitions provided in this project are potentially useful to somehow 'convert' to be usable in a pure Scala project, in order for that project to create a syntax highlight token stream from Scala 2 or Scala 3 sources.

Any entry points in such 'conversion'? I guess I have to somehow construct `java.util.regex.Matcher` objects from the different branches, and traverse the tree of matchers in some manner? Or use [joni](https://github.com/jruby/joni) or [tm4e.core](https://github.com/eclipse/tm4e/wiki/Core) perhaps?

**Comment by Sciss** [comment]
Ok, I tried tm4e.core now, and does seem to eat the `Scala.tmLanguage.json` file.

How does the selection between Scala 2 and Scala 3 happen? I don't see any obvious language version branching in the file.

**Comment by Sciss** [comment]
[Demo](https://github.com/dotterweide/dotterweide-exp-metals/blob/44621e4c0cf8cc1dbceeb53709248a12d081f3da/src/main/scala/dotterweide/metals/TextMateTest.scala)

**Comment by MaximeKjaer** [comment]
The project defines [TextMate grammars](https://macromates.com/manual/en/language_grammars) for both Scala 2 and Scala 3. You can read more about how VS Code uses these in [these docs](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#textmate-grammars).

There are multiple implementations of highlighters that use TextMate grammars; for instance GitHub has one, VS Code has one, and of course, TextMate has one too. So it would definitely be possible to write another pure Scala implementation. 
To implement such a highlighter, you would have to implement of a [pushdown automaton](https://en.wikipedia.org/wiki/Pushdown_automaton), which takes a description of the automaton in JSON format, and uses regexes to evaluate the transitions between states.

Do note however, that to be fully compliant with the TextMate grammar spec, you have to use a regex engine that supports a specific regex variant called [Oniguruma regular expressions](https://macromates.com/manual/en/regular_expressions). Note that not everybody does this correctly; for instance, GitHub [gets it wrong](https://github.com/scala/vscode-scala-syntax/pull/194#issuecomment-770377264). It is possible, however, that this is a conscious design decision; if you cannot use a Oniguruma regex engine for whatever reason, perhaps another engine can get you close to being correct.

Having a quick look at both joni and tm4e, it seems that tm4e basically implements the above.

We make no distinction between Scala 2 and Scala 3, the highlighter aims to work for both. It would be very difficult for our grammar to be able to distinguish one from the other, so we make no attempt to do so.

**Comment by Sciss** [comment]
Thank you for the explanation. Yes, it seems I can use tm4e now.
