### ISSUE TITLE
What is the relation between Scala.tmLanguage.json and Scala.tmLanguage.ts

### ISSUE THREAD

**Issue by Sciss** [scala/vscode-scala-syntax#205]
It seems to be as if `GenerateTmLanguageFile.ts` would synthesize `Scala.tmLanguage.ts` from `Scala.tmLanguage.json`, but [some recent commit](https://github.com/scala/vscode-scala-syntax/commit/e72b4c95debc2c38e509a7e9ee360de69245e8dd) is directly on the TypeScript file. Is the JSON the ground truth, or the TypeScript?

**Comment by MaximeKjaer** [comment]
The JSON contains the latest released version, but the TypeScript contains the latest development work. We build the JSON from the TS at every release.

You can read a bit more info in [the contributing docs](https://github.com/scala/vscode-scala-syntax/blob/main/CONTRIBUTING.md#building-the-project), and there's also some discussion as to why we do this in #23.

**Comment by Sciss** [comment]
Thanks. And how does it distinguish Scala 2 and 3, or is this only a Scala 2 grammar at the moment?

**Comment by MaximeKjaer** [comment]
Sorry, I replied over at #204 before I saw the question here, but here's the response to that question:

> We make no distinction between Scala 2 and Scala 3, the highlighter aims to work for both. It would be very difficult for our grammar to be able to distinguish one from the other, so we make no attempt to do so.
