### ISSUE TITLE
Quoted blocks with spaces fail to parse `' {`

### ISSUE THREAD

**Issue by lolgab** [scala/vscode-scala-syntax#226]
Quoted code with spaces between the `'` symbol and the `{` open brace, while being parsed correctly by the Scala compiler, are not parsed by vscode-scala-syntax, creating a all red coloring in VSCode and Github:
![example](https://user-images.githubusercontent.com/5793054/141379937-618dacde-2646-46f3-a8d9-8f262bfb2182.png)

**Comment by nicolasstucki** [comment]
This should actually not parse. You discovered a bug (lampepfl/dotty#13951).

The red coloring is expected as it is syntactically assumed to be an illegal `Char`. See https://github.com/scala/vscode-scala-syntax/blob/main/src/typescript/Scala.tmLanguage.ts#L859-L864
