### ISSUE TITLE
Accept soft modifiers separated by blank lines

### ISSUE THREAD

**Issue by nicolasstucki** [scala/vscode-scala-syntax#230]
See https://github.com/lampepfl/dotty/pull/14959

**Comment by Jentsch** [comment]
I don't think this can be accomplished correctly using tmlanguage.

From the [spec](https://macromates.com/manual/en/language_grammars#language_rules):

> Note that the regular expressions are matched against only a single line of the document at a time. That means it is not possible to use a pattern that matches multiple lines. [...]

The only way around that is to use a `begin` and `end` rule, but can't count the lines or see what's in between `begin` and `end`. Which prevents us from disquishing between this two cases:

```
// Should be highlighted  
transparent
inline def f2 = 2

// Should be not highlighted, because of the is empty line
transparent

inline def f3 = 3
```
(Shorted test case from scala/scala3#14959)

With this limitation in mind I see two options:
- Always color soft keywords as keywords regardless if they are actually keywords
- Only color soft keywords, if they are on the same line (current behaviour)

Out of those two option I think the current behaviour is the better one and those this issue can be closed as wont-fix.

**Comment by tgodzik** [comment]
Thanks for investigating! Semantic highlighting in scalameta/metals will also be able to help in this case
