### ISSUE TITLE
Opening paren matches with closing paren in character literal

### ISSUE THREAD

**Issue by sebbert** [scala/vscode-scala-syntax#25]
As of version 0.3.0, I get the following:

![Code_2019-05-12_19-27-49](https://user-images.githubusercontent.com/375907/57585715-2c8c3200-74ec-11e9-80d4-1143d9f10b4a.png)

**Comment by PanAeon** [comment]
Same problem with back-ticks:
![parens](https://user-images.githubusercontent.com/686076/60217077-bfe2b200-9863-11e9-9e6b-2c3a4ab2cede.png)

The only thing I've found is that a string literal  `")"` has got a special token type `String` and doesn't suffer from the issue. 

![token_2](https://user-images.githubusercontent.com/686076/60219008-fa028280-9868-11e9-81e4-9b8f7f03a0ce.png)



I suggest that we add a low priority scope `string.quoted.other` to the character literal, which will be shadowed by it's "proper scope" `constant.character.literal.scala`. This will mark token as `String` and apparently helps the issue:
![fixed](https://user-images.githubusercontent.com/686076/60219167-709f8000-9869-11e9-802f-3befa685ba81.png)

As for the backticks I think we should leave them as they are, as rules for them are scattered all over the code, and some vars in backticks shouldn't have any scope at all which prevents the use of above hack.

**Comment by olafurpg** [comment]
> I suggest that we add a low priority scope string.quoted.other to the character literal, which will be shadowed by it's "proper scope" constant.character.literal.scala. This will mark token as String and apparently helps the issue

This sounds like a reasonable approach. I suspect `')'` are much more common than backticked identifiers with parentheses.
