### ISSUE TITLE
support boolean and numeric values in using directives highlighting

### ISSUE THREAD

**Issue by bishabosha** [scala/vscode-scala-syntax#253]
```scala
//> using booleanKeys false, true
//> using numericKey -1

val foo = true
val bar = -1
```

`true` and `false` should also be highlighted the same as in the rhs of `foo`, currently they highlight like the directive's key. perhaps there is an priority issue because booleans (through `#constants`) are included in the matched patterns.

Additionally, in `-1` the `-` should be highlighted the same as in the rhs of `bar`, currently the `-` is the same colour as the directive's key. This seems to be because the `#constants` patterns do not include the leading negation sign

**Comment by nicolasstucki** [comment]
Aren't directives comma-separated strings?

**Comment by bishabosha** [comment]
I think this issue is resolved now - i.e. the highlighting is now as I expect - everything is a string, except booleans
