### ISSUE TITLE
`@main` not colored consistently

### ISSUE THREAD

**Issue by NoahELE** [scala/vscode-scala-syntax#272]
![image](https://github.com/user-attachments/assets/93f05ecc-4b7c-455d-b46a-504847a75185)

Just like the screenshot above, I'm not sure why the same annotation is colored differently.

The first has semantic token `class`, while the second has semantic token `other`

![image](https://github.com/user-attachments/assets/0da93fd4-3962-4cff-9092-31980df0694d)

![image](https://github.com/user-attachments/assets/4709a6c7-3543-43ea-974e-f29ad9e63f0a)

**Comment by tgodzik** [comment]
Thanks for reporting! Looks like this is an issue with semantic highlight from Metals 🤔 does it happen consistently? I can take a look next week.

**Comment by NoahELE** [comment]
Yes, this happens consistently, usually a call to `List` constructor will make the `@main` annotation turn gray. I'm not sure what triggered this exactly.

**Comment by tgodzik** [comment]
Could you post the whole sample? I don't think I can reproduce it currently.

**Comment by NoahELE** [comment]
```scala
@main def main1(): Unit =
  println("Hello, world!")

@main def main2(): Unit =
  val list = List(1, 2, 3)
  print(list)
```

with `"editor.semanticHighlighting.enabled": true` in vscode settings.

Some vscode color theme does not enable semantic highlighting by default. You can either turn it on manually in setting or use a default theme like `Default Dark Modern` which enable it by default. I guess that might be the cause.

**Comment by tgodzik** [comment]
Thanks, looks like this happens if a val is in the second main, which is super curious. Do you might opening the issue under scalameta/metals ? That's where the semantic highlight is implemented

**Comment by NoahELE** [comment]
Issue opened here https://github.com/scalameta/metals/issues/6823

**Comment by tgodzik** [comment]
Thanks!
