### ISSUE TITLE
fields with */ confused for comments

### ISSUE THREAD

**Issue by Cardu** [scala/vscode-scala-syntax#30]
version 0.3.2, following code compiles but is highlighted as a never-ending comment block:

![image](https://user-images.githubusercontent.com/4497461/58641815-3ee3d980-82fc-11e9-91b6-f359a530221b.png)

**Comment by jrudolph** [comment]
Github syntax highlighting is also confused about that one ;)

```scala
MediaRange.`*/*`

println("Test")
```

**Comment by olafurpg** [comment]
Fixing this issue here would also fix the syntax highlighting on GitHub, since this repository is a vendor for the Scala language in github/linguist.

**Comment by olafurpg** [comment]
This is has now been published to the Marketplace as v0.3.3
