### ISSUE TITLE
Single line block comments with embedded url fail to parse correctly

### ISSUE THREAD

**Issue by CloudNiner** [scala/vscode-scala-syntax#39]
vscode-scala-syntax version: 0.3.3

A block comment on a single line of the form:
```scala
/** https://github.com/scala/vscode-scala-syntax */
```
will fail to parse correctly. More specifically as long as the single line block comment has `://` highlighting will break:
![Screen Shot 2019-06-25 at 4 11 44 PM](https://user-images.githubusercontent.com/1818302/60129972-4ca64680-9764-11e9-992b-434486f9c931.png)

 Other combinations appear to parse correctly:
![Screen Shot 2019-06-25 at 4 11 52 PM](https://user-images.githubusercontent.com/1818302/60130001-57f97200-9764-11e9-825d-63fcdc5d35da.png)
![Screen Shot 2019-06-25 at 4 11 32 PM](https://user-images.githubusercontent.com/1818302/60130002-58920880-9764-11e9-95d0-9f22d361f227.png)

**Comment by PanAeon** [comment]
Yes, my bad. It's a regression from 0.3.2. :boom: The `//` symbol inside the block comment gets treated as a line comment and "consumes" the characters `*/`.
