### ISSUE TITLE
Security updates needed

### ISSUE THREAD

**Issue by SethTisue** [scala/vscode-scala-syntax#42]
is there a maintainer in this repo with the necessary knowhow to do something about the outdated/insecure libraries listed at https://github.com/scala/vscode-scala-syntax/network/alerts ? (I think the link is only visible to maintainers)

**Comment by SethTisue** [comment]
PR: #44

**Comment by nicolasstucki** [comment]
Unfortunately PR #44 will not fix all of the alert

**Comment by nicolasstucki** [comment]
Replaced with #45
