### ISSUE TITLE
Do not depend on github-changes

### ISSUE THREAD

**Issue by nicolasstucki** [scala/vscode-scala-syntax#45]
Last version was published 2 years ago and it has transitive dependencies that have security warnings .

https://www.npmjs.com/package/github-changes

**Comment by nicolasstucki** [comment]
We only use it here
https://github.com/scala/vscode-scala-syntax/blob/17a7bdb3a4a79406b5196fee4b6b9ba1e0613887/bin/ci-release.sh#L31

**Comment by nicolasstucki** [comment]
This code was copied from 
https://github.com/scalameta/metals-vscode/blob/65cf8d10638f437b966a216a9d27225b362dee46/.travis.yml#L29

**Comment by gabro** [comment]
@nicolasstucki that command generates https://github.com/scalameta/metals-vscode/blob/master/CHANGELOG.md

The library was picked arbitrarily (literally the first one that did the job I needed) so there may be newer alternatives.

That said, the library is not even used by the plugin, so you can avoid the security warning by removing the dependency and installing it ad-hoc in the CI.

Something like:

```
npx github-changes -o scalameta -r metals-vscode --no-merges -t "VSCode Extension Changelog" -k $GITHUB_TOKEN
```
