### ISSUE TITLE
Doesn't install into a remote dev container

### ISSUE THREAD

**Issue by adam-becker** [scala/vscode-scala-syntax#46]
This extension installs as a dependency of the `Scala (Metals)` extension, which I use in a remote development container. For some reason, though this extension won't install into the container, and has to be installed locally.

**Comment by PanAeon** [comment]
Hi, according to the https://code.visualstudio.com/api/advanced-topics/remote-extensions the grammar extensions fall into the UI category and should be installed to the local machine. I've never used containers before, so I'm not entirely sure.

**Comment by adam-becker** [comment]
tl;dr - The extension shouldn't force a usage pattern on you, let the user decide.

Every other language extension I've used (Including syntax highlighting) doesn't make this decision for you. The spirit of the remote development extension is that you can get an entire environment without any additional configuration by just opening a repository that's already set-up. Currently, there's extra steps involved including installing the extension on your host system.

**Comment by nicolasstucki** [comment]
This issue should be on https://github.com/scalameta/metals

**Comment by nicolasstucki** [comment]
@adam-becker could you report your issue on `Scala (Metals)` directly.

**Comment by nicolasstucki** [comment]
I agree that `Scala (Metals)` should probably not force this extension
