### ISSUE TITLE
Do not highlight some types as keywords

### ISSUE THREAD

**Issue by nicolasstucki** [scala/vscode-scala-syntax#62]
Currently `Unit`, `Boolean`, `Byte`, `Char`, `Short`, `Int`, `Float`, `Long`, `Double`, `String` and `Symbol` are colored as keywords. When written down it look like there is an error in the code. We should highlight them as types instead for homogeneity.

**Comment by nicolasstucki** [comment]
For example in [Symbol.scala#L33](https://github.com/scalameta/metals/blob/master/mtags/src/main/scala/scala/meta/internal/mtags/Symbol.scala#L33)

<img width="308" alt="Screenshot 2019-09-25 at 12 16 45" src="https://user-images.githubusercontent.com/3648029/65592170-5e2f0280-df8e-11e9-8903-07f2b59f1e1a.png">

the `Symbol` appears as a keyword. One could argue that this is highlighted as a `scala.Symbol` "primitive" but it is not as this symbol is defined that same file. It is impossible to distinguish them syntactically, only the language server could take the decision to display them with a specific style.

**Comment by martijnhoekstra** [comment]
if this is done, maybe `self` should stop being shown as a keyword too -- it's the reasoning of "not a keyword but sort of" as these I think.

**Comment by nicolasstucki** [comment]
Same for `None` and `Nil`
