### ISSUE TITLE
Artifacts not published to GitHub releases

### ISSUE THREAD

**Issue by sideeffffect** [scala/vscode-scala-syntax#75]
The releases pages on GitHub, eg
https://github.com/scala/vscode-scala-syntax/releases/tag/0.3.9
https://github.com/scala/vscode-scala-syntax/releases/tag/0.1.0
don't contain the build artifact, like `scala-lang.scala-0.3.9.vsix` and `scala-lang.scala-snippets-0.1.0.vsix`, uploaded and viable there

the `vsix` files is only available via Microsoft's Marketplace
https://marketplace.visualstudio.com/_apis/public/gallery/publishers/scalameta/vsextensions/metals/1.7.2/vspackage

That is not a viable source for other IDEs.
The `scala-lang.scala` and `scala-lang.scala-snippets` `vsix` files have to be available somewhere else, GitHub releases is probably the best place, so that Metals is officially included in Eclipse Che web IDE.
https://github.com/eclipse/che-plugin-registry/pull/356

Related issue: https://github.com/scalameta/metals/issues/1365

**Comment by sideeffffect** [comment]
Uploading the artifacts from Travis should be easy
https://docs.travis-ci.com/user/deployment/releases/

**Comment by sideeffffect** [comment]
@nicolasstucki could you please have a look at this? it's blocking [accepting Scala in Eclipse Che](https://github.com/eclipse/che-plugin-registry/pull/356)

**Comment by nicolasstucki** [comment]
I'm a bit swamped this next week. @anatoliykmetyuk could you have a look?

**Comment by nicolasstucki** [comment]
@sideeffffect I added manually the artifact to https://github.com/scala/vscode-scala-syntax/releases/tag/0.3.9

**Comment by sideeffffect** [comment]
That's great news, but I don't see it available for the newest release, like `0.3.11`. What went wrong?

**Comment by nicolasstucki** [comment]
The scripts to attached the `vsix` crashed
