### ISSUE TITLE
Adapt syntax highlighting to stabilized Dotty syntax

### ISSUE THREAD

**Issue by odersky** [scala/vscode-scala-syntax#76]
The Syntax from Dotty 0.22 on uses several new soft keywords that need to be properly syntax highlighed. In particular:

 - `extension` Ident? `on` (both `extension` and `on` should be highlighted)
 - `using` after opening "`(`"
 - `as` following a given signature. A given signature consists of `given`, an optional identifier, and optional type parameters `[...]` and context parameters `(using ...)`.
 - `open` as a soft modifier

**Comment by nicolasstucki** [comment]
Replaced with #91, #86, #87, #88
