### ISSUE TITLE
Is there any plan to contribute to Tree Sitter?

### ISSUE THREAD

**Issue by robsonpeixoto** [scala/vscode-scala-syntax#82]
> From http://tree-sitter.github.io/tree-sitter/

Tree-sitter is a parser generator tool and an incremental parsing library. It can build a concrete syntax tree for a source file and efficiently update the syntax tree as the source file is edited. Tree-sitter aims to be:
- General enough to parse any programming language
- Fast enough to parse on every keystroke in a text editor
- Robust enough to provide useful results even in the presence of syntax errors
- Dependency-free so that the runtime library (which is written in pure C) can be embedded in any application

The editor has or native support or has a extension that add support:
- Atom: https://github.blog/2018-10-31-atoms-new-parsing-system/
- Neovim: https://neovim.io/roadmap/ - on the next version
- vscode: https://marketplace.visualstudio.com/items?itemName=georgewfraser.vscode-tree-sitter
- emacs: https://github.com/ubolonton/emacs-tree-sitter

And is there an incomplete parser here: https://github.com/tree-sitter/tree-sitter-scala
Are there any plans to help on this parse or create your own? It will be one job that could be used by a lot of editors.

**Comment by olafurpg** [comment]
Thank you for reporting! I believe tree-sitter is the future for a lot of exciting dev tooling and I would love to have it support Scala. I’m not aware of any ongoing effort to make the current scala support “production ready”, but I want to register myself interested if somebody is working on it.

**Comment by robsonpeixoto** [comment]
vscode implemented [Semantic Highlight](https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide) and because of that probably the vscode-tree-sitter will be deprecated https://github.com/georgewfraser/vscode-tree-sitter/issues/30#issuecomment-640270518
